services:
  # --- INFRAESTRUCTURA Y BASES DE DATOS ---
  nexusai-db:
    image: postgres:16
    container_name: nexusai-db
    environment:
      POSTGRES_DB: nexusai
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    networks:
      - nexus-network

  kafka:
    image: bitnami/kafka:latest # 'latest' siempre est√° disponible y evita errores de tag
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - nexus-network

  chroma-db:
    image: chromadb/chroma:latest
    container_name: chroma-db
    ports:
      - "8001:8000"
    volumes:
      - ./infra/chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=FALSE
    networks:
      - nexus-network

  # --- MICROSERVICIOS ---
  core-engine:
    build:
      context: ./core-engine
      dockerfile: Dockerfile
    container_name: core-engine
    depends_on:
      - nexusai-db
      - kafka
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://nexusai-db:5432/nexusai
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - nexus-network

  ai-agent-python:
    build:
      context: ./ai-agent-python
      dockerfile: Dockerfile
    container_name: ai-agent-python
    depends_on:
      - chroma-db
    ports:
      - "8000:8000"
    env_file: ./ai-agent-python/.env
    networks:
      - nexus-network

  token-watcher:
    build:
      context: ./token-watcher-go
      dockerfile: Dockerfile
    container_name: token-watcher
    ports:
      - "8081:8081"
    networks:
      - nexus-network

  # --- OBSERVABILIDAD ---
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - nexus-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./infra/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - nexus-network

networks:
  nexus-network:
    driver: bridge