global:
  scrape_interval: 5s # Cada 5 segundos pedir√° datos

scrape_configs:
  - job_name: 'spring-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080'] # El backend de Java

  - job_name: 'python-ai-agent'
    static_configs:
      - targets: ['host.docker.internal:8000'] # El servicio de Python